// <auto-generated />
namespace MvcFolhetos.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Sequencefolhetos : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Sequencefolhetos));
        
        string IMigrationMetadata.Id
        {
            get { return "201809202049066_Sequence-folhetos"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
